foreground            #cdd6f4
background            #1c1c1c
selection_foreground  #1e1e2e
selection_background  #585b70

cursor                #f5e0dc
cursor_text_color     #1e1e2e

url_color             #94e2d5

active_border_color   #81a2be
inactive_border_color #45475a
bell_border_color     #f9e2af

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #1e1e2e
active_tab_background   #81a2be
inactive_tab_foreground #bac2de
inactive_tab_background #313244
tab_bar_background      #181825

mark1_foreground #1e1e2e
mark1_background #81a2be
mark2_foreground #1e1e2e
mark2_background #b294bb
mark3_foreground #1e1e2e
mark3_background #a4ac5f

color0  #45475a
color8  #585b70

color1  #c46262
color9  #cc6666

color2  #a4ac5f
color10 #b9ca4a

color3  #f0c674
color11 #ebd391

color4  #7897b1
color12 #7aa6da

color5  #b294bb
color13 #f2aede

color6  #94e2d5
color14 #6bd7ca

color7  #a6adc8
color15 #bac2de
