vim.g.colors_name = "custom"

local bg = "#1c1c1c"
local bg_alt = "#1c1c1c"
local fg = "#abb2bf"
local grey = "#5c6370"
local light_grey = "#848b98"
local black = "#181a1f"

local red = "#e86671"
local orange = "#d19a66"
local yellow = "#e5c07b"
local green = "#98c379"
local cyan = "#56b6c2"
local blue = "#81a2be"
local purple = "#c678dd"

local diff_add = "#31392b"
local diff_delete = "#382b2c"
local diff_change = "#1c3448"
local diff_text = "#2c5372"

local function hl(group, attrs)
  vim.api.nvim_set_hl(0, group, attrs)
end

local function link(from, to)
  vim.api.nvim_set_hl(0, from, { link = to, default = true })
end

-- Base
hl("Normal", { fg = fg, bg = bg })
hl("NormalNC", { fg = fg, bg = bg })
hl("NormalFloat", { fg = fg, bg = bg_alt })
hl("FloatBorder", { fg = blue, bg = bg_alt })
hl("FloatTitle", { fg = blue, bg = bg_alt })
hl("ColorColumn", { bg = bg_alt })
hl("CursorColumn", { bg = bg_alt })
hl("CursorLine", { bg = "#2e2e32" })
hl("CursorLineNr", { fg = yellow })

-- Mode indicator (modicator.nvim)
hl("NormalMode", { fg = blue })
hl("InsertMode", { fg = green })
hl("VisualMode", { fg = yellow })
hl("CommandMode", { fg = purple })
hl("ReplaceMode", { fg = orange })
hl("SelectMode", { fg = purple })
hl("TerminalMode", { fg = cyan })
hl("TerminalNormalMode", { fg = blue })
hl("LineNr", { fg = grey })
hl("Cursor", { fg = bg, bg = fg })
hl("MatchParen", { bg = bg_alt })
hl("NonText", { fg = grey })
hl("Whitespace", { fg = bg_alt })
hl("SpecialKey", { fg = cyan })
hl("Conceal", { fg = grey, bg = bg_alt })
hl("SignColumn", { fg = grey, bg = bg })
hl("EndOfBuffer", { fg = bg })
hl("Folded", { fg = light_grey, bg = bg_alt })
hl("FoldColumn", { fg = grey, bg = bg })
hl("VertSplit", { fg = grey, bg = bg })
hl("WinSeparator", { fg = bg_alt, bg = bg })
hl("StatusLine", { fg = fg, bg = bg_alt })
hl("StatusLineNC", { fg = grey, bg = bg })
hl("TabLine", { fg = fg, bg = bg_alt })
hl("TabLineFill", { fg = grey, bg = bg_alt })
hl("TabLineSel", { fg = bg, bg = fg })
hl("Title", { fg = blue })
hl("Directory", { fg = blue })
hl("ErrorMsg", { fg = red })
hl("WarningMsg", { fg = yellow })
hl("ModeMsg", { fg = light_grey })
hl("MoreMsg", { fg = green })
hl("Question", { fg = purple })
hl("Todo", { fg = orange })

-- Search
hl("Search", { fg = bg, bg = yellow })
hl("IncSearch", { fg = bg, bg = orange })
hl("CurSearch", { fg = bg, bg = orange })
hl("Substitute", { fg = bg, bg = green })

-- Visual / selection
hl("Visual", { bg = "#2e2e32" })
hl("VisualNOS", { fg = fg, bg = bg_alt, underline = true })
hl("WildMenu", { fg = bg, bg = blue })

-- Popup menu
hl("Pmenu", { fg = fg, bg = "#1c1c1c" })
hl("PmenuSel", { fg = fg, bg = "#2e2e32", bold = true })
hl("PmenuSbar", { bg = "#1c1c1c" })
hl("PmenuThumb", { bg = grey })
hl("PmenuMatch", { fg = cyan, bg = "#1c1c1c" })
hl("PmenuMatchSel", { fg = fg, bg = "#2e2e32", bold = true })

-- Syntax
hl("Comment", { fg = grey, italic = true })
hl("Constant", { fg = orange })
hl("String", { fg = green })
hl("Character", { fg = green })
hl("Number", { fg = orange })
hl("Boolean", { fg = orange })
hl("Float", { fg = orange })
hl("Identifier", { fg = red })
hl("Function", { fg = blue })
hl("Statement", { fg = purple })
hl("Conditional", { fg = purple })
hl("Repeat", { fg = purple })
hl("Label", { fg = cyan })
hl("Operator", { fg = cyan })
hl("Keyword", { fg = purple })
hl("Exception", { fg = purple })
hl("PreProc", { fg = yellow })
hl("Include", { fg = blue })
hl("Define", { fg = purple })
hl("Macro", { fg = yellow })
hl("PreCondit", { fg = yellow })
hl("Type", { fg = yellow })
hl("StorageClass", { fg = orange })
hl("Structure", { fg = yellow })
hl("Typedef", { fg = yellow })
hl("Special", { fg = cyan })
hl("SpecialChar", { fg = cyan })
hl("Tag", { fg = blue })
hl("Delimiter", { fg = fg })
hl("SpecialComment", { fg = grey })
hl("Debug", { fg = yellow })
hl("Underlined", { fg = blue, underline = true })
hl("Bold", { bold = true })
hl("Italic", { italic = true })

-- Diagnostics
hl("DiagnosticError", { fg = red })
hl("DiagnosticWarn", { fg = yellow })
hl("DiagnosticInfo", { fg = light_grey })
hl("DiagnosticHint", { fg = cyan })
hl("DiagnosticOk", { fg = green })
hl("DiagnosticUnderlineError", { undercurl = true, sp = red })
hl("DiagnosticUnderlineWarn", { undercurl = true, sp = yellow })
hl("DiagnosticUnderlineInfo", { undercurl = true, sp = light_grey })
hl("DiagnosticUnderlineHint", { undercurl = true, sp = cyan })
hl("DiagnosticUnnecessary", { fg = grey })
link("DiagnosticVirtualTextError", "DiagnosticError")
link("DiagnosticVirtualTextWarn", "DiagnosticWarn")
link("DiagnosticVirtualTextInfo", "DiagnosticInfo")
link("DiagnosticVirtualTextHint", "DiagnosticHint")
link("DiagnosticSignError", "DiagnosticError")
link("DiagnosticSignWarn", "DiagnosticWarn")
link("DiagnosticSignInfo", "DiagnosticInfo")
link("DiagnosticSignHint", "DiagnosticHint")

-- LSP
hl("LspReferenceText", { underdouble = true, sp = grey })
hl("LspReferenceRead", { underdouble = true, sp = cyan })
hl("LspReferenceWrite", { underdouble = true, sp = orange })
hl("LspCodeLens", { fg = grey })
hl("LspCodeLensSeparator", { fg = grey })
hl("LspInfoBorder", { fg = blue })
hl("LspSignatureActiveParameter", { bold = true, underline = true })

-- Diff
hl("DiffAdd", { bg = diff_add })
hl("DiffDelete", { bg = diff_delete })
hl("DiffChange", { bg = diff_change })
hl("DiffText", { fg = fg, bg = diff_text })

-- Treesitter
hl("@comment", { fg = grey, italic = true })
hl("@comment.todo", { fg = orange, bold = true })
hl("@comment.error", { fg = red, bold = true })
hl("@comment.warning", { fg = yellow, bold = true })
hl("@comment.note", { fg = blue, bold = true })
hl("@error", { fg = red })
hl("@none", { fg = fg })
hl("@preproc", { fg = yellow })
hl("@define", { fg = purple })
hl("@operator", { fg = cyan })
hl("@punctuation.delimiter", { fg = fg })
hl("@punctuation.bracket", { fg = light_grey })
hl("@punctuation.special", { fg = cyan })
hl("@string", { fg = green })
hl("@string.regex", { fg = cyan })
hl("@string.escape", { fg = orange })
hl("@string.special", { fg = green })
hl("@character", { fg = green })
hl("@character.special", { fg = orange })
hl("@boolean", { fg = orange })
hl("@number", { fg = orange })
hl("@float", { fg = orange })
hl("@function", { fg = blue })
hl("@function.call", { fg = blue })
hl("@function.builtin", { fg = cyan })
hl("@function.macro", { fg = yellow })
hl("@method", { fg = blue })
hl("@method.call", { fg = blue })
hl("@constructor", { fg = yellow })
hl("@parameter", { fg = red })
hl("@parameter.reference", { fg = red })
hl("@variable", { fg = fg })
hl("@variable.builtin", { fg = red })
hl("@variable.parameter", { fg = red })
hl("@variable.member", { fg = fg })
hl("@constant", { fg = orange })
hl("@constant.builtin", { fg = orange })
hl("@constant.macro", { fg = yellow })
hl("@property", { fg = fg })
hl("@field", { fg = fg })
hl("@field.macro", { fg = yellow })
hl("@symbol", { fg = cyan })
hl("@symbol.builtin", { fg = red })
hl("@keyword", { fg = purple })
hl("@keyword.return", { fg = purple })
hl("@keyword.function", { fg = purple })
hl("@keyword.operator", { fg = purple })
hl("@keyword.conditional", { fg = purple })
hl("@keyword.repeat", { fg = purple })
hl("@keyword.debug", { fg = orange })
hl("@keyword.exception", { fg = purple })
hl("@keyword.import", { fg = yellow })
hl("@keyword.type", { fg = yellow })
hl("@keyword.storage", { fg = purple })
hl("@keyword.modifier", { fg = purple })
hl("@conditional", { fg = purple })
hl("@repeat", { fg = purple })
hl("@label", { fg = cyan })
hl("@include", { fg = blue })
hl("@exception", { fg = purple })
hl("@type", { fg = yellow })
hl("@type.builtin", { fg = yellow })
hl("@type.qualifier", { fg = yellow })
hl("@type.definition", { fg = yellow })
hl("@storageclass", { fg = orange })
hl("@attribute", { fg = cyan })
hl("@decorator", { fg = cyan })
hl("@annotation", { fg = cyan })
hl("@namespace", { fg = yellow })
hl("@module", { fg = yellow })
hl("@tag", { fg = blue })
hl("@tag.attribute", { fg = yellow })
hl("@tag.delimiter", { fg = grey })
hl("@tag.builtin", { fg = blue })
hl("@tag.attribute.ts", { fg = yellow })

-- Neo-tree
hl("NeoTreeNormal", { fg = fg, bg = bg })
hl("NeoTreeNormalNC", { fg = fg, bg = bg })
hl("NeoTreeCursorLine", { bg = "#2e2e32" })
hl("NeoTreeFloatBorder", { fg = blue, bg = bg_alt })
hl("NeoTreeFloatTitle", { fg = blue })
hl("NeoTreeRootName", { fg = yellow, bold = true })
hl("NeoTreeFileName", { fg = fg })
hl("NeoTreeFileNameOpened", { fg = blue })
hl("NeoTreeDirectoryIcon", { fg = blue })
hl("NeoTreeDirectoryName", { fg = blue })
hl("NeoTreeFileIcon", { fg = light_grey })
hl("NeoTreeIndentMarker", { fg = grey })
hl("NeoTreeExpander", { fg = grey })
hl("NeoTreeSymbolicLinkTarget", { fg = yellow })
hl("NeoTreeGitAdded", { fg = green })
hl("NeoTreeGitModified", { fg = yellow })
hl("NeoTreeGitDeleted", { fg = red })
hl("NeoTreeGitUntracked", { fg = light_grey })
hl("NeoTreeGitIgnored", { fg = grey })
hl("NeoTreeTitleBar", { fg = bg, bg = blue })
hl("NeoTreeTitleBarProvider", { fg = bg, bg = blue })
hl("NeoTreeDimText", { fg = grey })

-- Gitsigns
hl("GitSignsAdd", { fg = green, bg = bg })
hl("GitSignsChange", { fg = yellow, bg = bg })
hl("GitSignsDelete", { fg = red, bg = bg })
hl("GitSignsAddLn", { fg = green })
hl("GitSignsChangeLn", { fg = yellow })
hl("GitSignsDeleteLn", { fg = red })
hl("GitSignsUntracked", { fg = light_grey })

-- Telescope
hl("TelescopeNormal", { fg = fg, bg = bg_alt })
hl("TelescopeBorder", { fg = blue, bg = bg_alt })
hl("TelescopePromptNormal", { fg = fg, bg = bg_alt })
hl("TelescopePromptBorder", { fg = blue, bg = bg_alt })
hl("TelescopePromptPrefix", { fg = blue })
hl("TelescopeTitle", { fg = bg, bg = blue })
hl("TelescopePreviewTitle", { fg = bg, bg = green })
hl("TelescopePromptTitle", { fg = bg, bg = blue })
hl("TelescopeResultsTitle", { fg = bg, bg = blue })
hl("TelescopeSelection", { fg = fg, bg = "#2e2e32" })
hl("TelescopeSelectionCaret", { fg = blue })
hl("TelescopeMultiSelection", { fg = yellow })
hl("TelescopeMatching", { fg = cyan, bold = true })

-- nvim-cmp
hl("CmpItemAbbr", { fg = fg })
hl("CmpItemAbbrDeprecated", { fg = grey, strikethrough = true })
hl("CmpItemAbbrMatch", { fg = cyan })
hl("CmpItemAbbrMatchFuzzy", { fg = cyan })
hl("CmpItemMenu", { fg = light_grey })
hl("CmpItemKindText", { fg = fg })
hl("CmpItemKindMethod", { fg = blue })
hl("CmpItemKindFunction", { fg = blue })
hl("CmpItemKindConstructor", { fg = yellow })
hl("CmpItemKindField", { fg = fg })
hl("CmpItemKindVariable", { fg = red })
hl("CmpItemKindClass", { fg = yellow })
hl("CmpItemKindInterface", { fg = yellow })
hl("CmpItemKindModule", { fg = yellow })
hl("CmpItemKindProperty", { fg = fg })
hl("CmpItemKindUnit", { fg = orange })
hl("CmpItemKindValue", { fg = orange })
hl("CmpItemKindEnum", { fg = yellow })
hl("CmpItemKindKeyword", { fg = purple })
hl("CmpItemKindSnippet", { fg = orange })
hl("CmpItemKindColor", { fg = purple })
hl("CmpItemKindFile", { fg = blue })
hl("CmpItemKindReference", { fg = purple })
hl("CmpItemKindFolder", { fg = blue })
hl("CmpItemKindEnumMember", { fg = orange })
hl("CmpItemKindConstant", { fg = orange })
hl("CmpItemKindStruct", { fg = yellow })
hl("CmpItemKindEvent", { fg = yellow })
hl("CmpItemKindOperator", { fg = cyan })
hl("CmpItemKindTypeParameter", { fg = yellow })

-- nvim-notify
hl("NotifyERRORTitle", { fg = red, bg = "NONE", bold = true })
hl("NotifyWARNTitle", { fg = yellow, bg = "NONE", bold = true })
hl("NotifyINFOTitle", { fg = blue, bg = "NONE", bold = true })
hl("NotifyDEBUGTitle", { fg = light_grey, bg = "NONE", bold = true })
hl("NotifyTRACETitle", { fg = purple, bg = "NONE", bold = true })
hl("NotifyERRORBorder", { fg = red })
hl("NotifyWARNBorder", { fg = yellow })
hl("NotifyINFOBorder", { fg = blue })
hl("NotifyDEBUGBorder", { fg = light_grey })
hl("NotifyTRACEBorder", { fg = purple })
hl("NotifyERRORBody", { fg = fg, bg = "NONE" })
hl("NotifyWARNBody", { fg = fg, bg = "NONE" })
hl("NotifyINFOBody", { fg = fg, bg = "NONE" })
hl("NotifyDEBUGBody", { fg = fg, bg = "NONE" })
hl("NotifyTRACEBody", { fg = fg, bg = "NONE" })

-- Noice
hl("NoiceCmdlinePopupBorder", { fg = blue, bg = bg_alt })
hl("NoiceCmdlinePopupTitle", { fg = blue, bg = bg_alt })
hl("NoiceCursor", { fg = bg, bg = fg })

-- lazy.nvim
hl("LazyButton", { fg = bg, bg = blue })
hl("LazyButtonActive", { fg = bg, bg = yellow })
hl("LazyH1", { fg = blue, bold = true })
hl("LazyH2", { fg = yellow })
